repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: check-toml

  - repo: local
    hooks:
      - id: format
        name: format
        entry: make format
        language: system
        types: [ python ]

      - id: isort
        name: sort-imports
        entry: make sort-imports
        language: system
        types: [ python ]

      - id: lint
        name: lint
        entry: make lint
        language: system
        types: [ python ]
