target-version = "py312"


# Maximum line length (compatible with Black)
line-length = 88
indent-width = 4

# Directories to exclude from linting
exclude = [".git", ".venv", "build", "dist", "__pycache__"]

[lint]
# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
select = ["E", "F", "I"]

# Ignore line length violations.
ignore = ["E501"]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["A", "B", "C", "D", "E", "F", "I"]
unfixable = []

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"